<?php

namespace ContactBundle\Repository;

use Symfony\Bridge\Doctrine\RegistryInterface;
use ContactBundle\Entity\Contact;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends ServiceEntityRepository
{
    /**
     * ProfilesRepository constructor.
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Contact::class);
    }

    public function create(Contact $contact): bool
    {
        try {
            $this->_em->persist($contact);
            $this->_em->flush($contact);

            return true;
        } catch (\Doctrine\ORM\ORMException | \Exception | \Doctrine\ORM\OptimisticLockException $e) {

            return false;
        }
    }

}
